#!/bin/bash

# 检查Release Workflow状态的脚本

echo "==================================="
echo "Release Workflow 状态检查"
echo "==================================="
echo ""

echo "请访问以下链接查看workflow运行状态："
echo ""
echo "1. 所有workflow运行记录："
echo "   https://github.com/wayfind/intent-engine/actions"
echo ""
echo "2. Release workflow运行记录："
echo "   https://github.com/wayfind/intent-engine/actions/workflows/release.yml"
echo ""
echo "3. v0.1.2 release页面："
echo "   https://github.com/wayfind/intent-engine/releases/tag/v0.1.2"
echo ""

echo "==================================="
echo "检查清单："
echo "==================================="
echo ""
echo "□ Release workflow是否已触发？"
echo "  - 查看Actions页面，搜索 'v0.1.2'"
echo ""
echo "□ Workflow是否正在运行？"
echo "  - 状态为黄色圆圈 = 运行中（需等待30-40分钟）"
echo "  - 状态为绿色勾号 = 成功"
echo "  - 状态为红色叉号 = 失败"
echo ""
echo "□ 如果workflow成功，检查release页面"
echo "  - 应该看到5个二进制文件附件"
echo "  - intent-engine-linux-x86_64.tar.gz"
echo "  - intent-engine-linux-aarch64.tar.gz"
echo "  - intent-engine-macos-x86_64.tar.gz"
echo "  - intent-engine-macos-aarch64.tar.gz"
echo "  - intent-engine-windows-x86_64.exe.zip"
echo ""

echo "==================================="
echo "可能的问题及解决方案："
echo "==================================="
echo ""
echo "问题1: Workflow没有触发"
echo "  解决: Tag可能没有正确推送，尝试重新推送tag"
echo ""
echo "问题2: Workflow正在运行"
echo "  解决: 等待构建完成（约30-40分钟）"
echo ""
echo "问题3: Workflow失败"
echo "  解决: 点击失败的workflow查看错误日志"
echo ""
echo "问题4: Workflow成功但没有附件"
echo "  解决: 检查workflow配置中的artifact上传步骤"
echo ""
